source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/1_core_13CO2_import_data.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/2_core_13CO2_bolus_injection.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/3_core_13CO2_infusion_physiology_basics.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/4_core_serum_labeling_import data.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/5_core_labeling_analysis.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/6_core_consumption_flux.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/7_core_production_flux.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/8_core_flux extrapolation.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/9_core_ATP_estimate.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/10_core_draw flux network.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/11_core_draw flux network_highlight.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/12_core_draw flux network, interactive.R")
source("/Users/boyuan/Desktop/Harvard/Manuscript/1. fluxomics/raw data/13_validation_experiment.R")
