---
title: "labeling fraction"
output: html_document
date: "2023-04-20"
---

```{r, message=F, warning=FALSE,fig.height=6, fig.width=10, dpi=300, echo=F, results=F, fig.show='hide'}
library(ComplexHeatmap)
library(scales) # for color scale
library(mgcv)
library(ggpmisc)
library(ggbeeswarm)
library(readxl)
library(RColorBrewer)
library(viridis)
library(ggsci)
library(rebus)
library(matrixStats)
library(limSolve)
library(xlsx)
library(cowplot)

library(tidyverse)



# Load my own R package vivoFlux
setwd("/Users/boyuan/Desktop/Harvard/Research/vivoFlux")
devtools::load_all()
set.seed(2012)


theme.mybw <- theme_bw() + theme(strip.background = element_blank(),
                                 strip.text = element_text(size = 14, face = "bold"),
                                 axis.text = element_text(size = 13, color = "black"),
                                 axis.text.x = element_text(angle = 45, hjust = 1),
                                 panel.grid = element_blank(),
                                 plot.title = element_text(hjust = .5, face = "bold", size = 14),
                                 axis.title = element_text(size = 14, face = "bold"),
                                 panel.spacing = unit(10, "mm"))

theme.myClassic <-  theme_classic() +  theme(strip.background = element_blank(),
                                             axis.text = element_text(colour = "black", size=13),
                                             axis.title = element_text(colour = "black", size = 13, face = "bold"),
                                             strip.text = element_text(colour = "black", size = 14, face = "bold"),
                                             legend.text = element_text(colour = "black", size = 12),
                                             plot.title = element_text(size = 14, hjust = .5, face = "bold"),
                                             legend.title = element_blank(),
                                             panel.spacing = unit(10, "mm"))

ordered.phenotype = factor(c("WT", "HFD", "ob/ob",  "db/db"), ordered = T)
color.phenotype = c("snow4", "chocolate1", "deepskyblue3",  "firebrick2")
color.phenotype %>% show_col()
names(color.phenotype) = ordered.phenotype


ordered.Compound = c("Glucose", "Lactate",  "Glycerol","Alanine", "Glutamine", "3-Hydroxybutyric acid", "Acetate", 
                     "C16:0", "C18:1", "C18:2", "Valine",
                     "storage", "CO2", "non-Ox sink")

ordered.Compound.abbreviated = ordered.Compound %>% str_replace("3-Hydroxybutyric acid", "3-HB")

ordered.gluconeogenic.Set = ordered.Compound[1:5]

color.Compounds = c(pal_nejm()(7), 
                    "seashell", "papayawhip",  "peachpuff", "firebrick3",
                    "grey", "whitesmoke",  "slategrey")

color.Compounds[1] <- "tomato"
color.Compounds[2] <- "turquoise3"
color.Compounds[3] <- "khaki1"
color.Compounds[4] <- "olivedrab4" # "lightseagreen"
color.Compounds[5] <- "mistyrose"

color.Compounds %>% show_col()
# pal_nejm()(7) %>% show_col()

# c("#0072B5FF", "steelblue") %>% show_col()
# c("#0072B5FF", "steelblue") %>% show_col()

names(color.Compounds) = ordered.Compound








# Mouse infusion overview
ph = c("WT", "ob/ob", "HFD", "db/db")
names(ph) = c("L", "O", "H", "d")




# Basic mouse and sample documentation
path.infusion.surgery = "/Users/boyuan/Desktop/Harvard/Research/db db mice/Infusion data/infusion rounds data.xlsx"
d.mouse = read_excel(path.infusion.surgery, sheet = "mouse data")
d.infusion_rounds = read_excel(path = path.infusion.surgery, sheet = "infusion rounds",
                               # skip = 7, 
                               
                               range = "A8:O468")
d.standardInfusionParameters = read_excel(path.infusion.surgery, sheet = "infusion parameters")


# Labeling data =======
path.labeling = "/Users/boyuan/Desktop/Harvard/Research/db db mice/Infusion data/2021_Nov_gluc_lact.xlsm"

d.LCMS_sampleInfo = read_excel(path.labeling, sheet = "sample_info") %>% select( - RU_code)
# Check there is no duplicated rows
if (d.LCMS_sampleInfo %>% duplicated() %>% sum() >0) stop("There is duplicated rows in the mouse_ID dataset.")

d = read_excel(path.labeling, sheet = "a_h")
d = d %>% select( - contains("d-")) %>% # remove infusion round d; likely cross contamination of artery blood by tracer residual on the button; ca. 80% labeling in art. blood
  select( - contains( "a-tail-d1")) %>% # mouse jumped out of cage and fell from table to floor during infusion; ca. only 5% M+6 glucose labeling, aberrantly low; 
  select(-c(Q1,Q2, Q3, Q4)) # remove quality control samples

# background subtraction & natural abundance correction
d.backgroundSubtracted = d %>% flx.subtract_background(blankSamples = c("blank1", "blank2", "blank3", "blank4", "blank_2ndSeq"))
list.corrected = d.backgroundSubtracted %>% flx.correct_natural_abundance()

# combine infusion and sample ID data
func.combine_sample_ID = function(dataset.tidy){
  d.tidy = dataset.tidy %>% 
    mutate(mouse_ID = str_extract(sample, pattern = WRD %R% one_or_more(DIGIT) %R% END), # L/O/d, with mouse number within phenotype
           infusion_round = str_extract(sample, START %R% one_or_more(WRD) )) %>%
    left_join(d.LCMS_sampleInfo, by = c("sample", "infusion_round", "mouse_ID")) %>% 
    left_join(d.infusion_rounds, by = c("infusion_round", "mouse_ID")) 
  return(d.tidy)
} 

d.normalized.tidy.1 = func.combine_sample_ID(dataset.tidy = list.corrected$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.1 = func.combine_sample_ID(dataset = list.corrected$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))





# Sheet 2: RU analysis in Feb 2022
list.corrected.2 = read_excel(path.labeling, sheet = "RU_x-aa") %>% 
  select(-c("z-tail-O1","aa-art-O3", "aa-tail-O3")) %>%  # glucose labeling only 3~4%; signifiant mice age by time of infusion, button leaking in O1 in Dec 2021 - Feb 2022 glucose clamp study; 
  flx.subtract_background(blankSamples =  c("Blank1",	"Blank3",	"Blank4")) %>% 
  natural_abundance_correction(resolution = 70000)

d.normalized.tidy.2 = func.combine_sample_ID(dataset.tidy = list.corrected.2$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.2 = func.combine_sample_ID(dataset = list.corrected.2$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))





# Sheet 3: RU analysis in March 2022, analyzed by Rutgers with resolution of 70,000
list.corrected.3 = read_excel(path.labeling, sheet = "RU_i-n") %>% 
  flx.subtract_background(blankSamples =  paste0("Blank", 3:9)) %>% 
  natural_abundance_correction(resolution = 70000)

d.normalized.tidy.3 = func.combine_sample_ID(dataset.tidy = list.corrected.3$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.3 = func.combine_sample_ID(dataset = list.corrected.3$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))




# Sheet 4: clamp data, basal & clamp
d4 = read_excel(path.labeling, sheet = "clamp_af-ah") %>% select(!contains("-2"))  # remove -2 (being the enrichment at the end of the clamp)

# rename file names to be consistent with the general naming rule
d4.1 = d4[, 1:3] # first three columns
d4.2 = d4[, 4:ncol(d4)]
d4.rounds = colnames(d4.2) %>% str_extract(pattern = START %R% one_or_more(WRD))
d4.mouse =  colnames(d4.2) %>% str_extract(pattern = "-" %R% one_or_more(WRD) %R% one_or_more(DGT) ) %>% str_remove("-")
d4.2.filenames = d4.rounds %>% str_c("-tail-", d4.mouse)
d4.2.filenames[28:32] = paste0("blank", 1:5)
colnames(d4.2) = d4.2.filenames
d4 = cbind(d4.1, d4.2) %>% as_tibble()

list.corrected.4 = d4 %>% 
  flx.subtract_background(blankSamples =  paste0("blank", 1:5)) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.4 = func.combine_sample_ID(dataset.tidy = list.corrected.4$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.4 = func.combine_sample_ID(dataset = list.corrected.4$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))




# Sheet 5: Glycerol-3P
list.corrected.5 = read_excel(path.labeling, sheet = "G3P_o-p") %>% 
  
  # remove outlier samples
  select(-`p-tail-d5`) %>% 
  
  flx.subtract_background(blankSamples =  paste0("blank_glycerol3P_", 1:3)) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.5 = func.combine_sample_ID(dataset.tidy = list.corrected.5$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.5 = func.combine_sample_ID(dataset = list.corrected.5$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))

# remove artery sample due to contamination from lock solution; so much higher labeling in venous blood than artery blood due to dilution by lock solution-glycerol
d.normalized.tidy.5 = d.normalized.tidy.5 %>% filter(sample %>% str_detect("tail"))
d.corrected.tidy.5 = d.corrected.tidy.5 %>% filter(sample %>% str_detect("tail"))




# Sheet 6: r to w
list.corrected.6 = read_excel(path.labeling, sheet = "o-p-r-s-t-u-v-w") %>% 
  flx.subtract_background(blankSamples =  paste0("blank_", 6:9)) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.6 = func.combine_sample_ID(dataset.tidy = list.corrected.6$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.6 = func.combine_sample_ID(dataset = list.corrected.6$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))




# Sheet 7: glycerol 3-P, rounds # a to n;  q to z
list.corrected.7 = read_excel(path.labeling, sheet = "G3P_a-n_q-z-aa-ae") %>% 
  flx.subtract_background(blankSamples =  c("blank2", "blank4")) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.7 = func.combine_sample_ID(dataset.tidy = list.corrected.7$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.7 = func.combine_sample_ID(dataset = list.corrected.7$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))


# Sheet 8: gluconeogenic, ab, ac, ad
list.corrected.8 = read_excel(path.labeling, sheet = "ab_ac_ad") %>% 
  flx.subtract_background(blankSamples =  paste0("blank", 1:6) ) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.8 = func.combine_sample_ID(dataset.tidy = list.corrected.8$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.8 = func.combine_sample_ID(dataset = list.corrected.8$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))



# Sheet 9:  glycerol 3-P & FA & HILIC metabolites, rounds # am to ao
list.corrected.9 = read_excel(path.labeling, sheet = "G3P_HILIC_am-ao") %>% 
  flx.subtract_background(blankSamples =  paste0("blk", 1:3) ) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.9 = func.combine_sample_ID(dataset.tidy = list.corrected.9$Normalized %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.9 = func.combine_sample_ID(dataset = list.corrected.9$Corrected %>% 
                                              gather(-c(Compound, C_Label), key = sample, value = intensity))







# Sheet 10:  glycerol 3-P, rounds # ar to bd
list.corrected.10 = read_excel(path.labeling, sheet = "G3P_ar_bd") %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.10 = func.combine_sample_ID(dataset.tidy = list.corrected.10$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.10 = func.combine_sample_ID(dataset = list.corrected.10$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))


# Sheet 11:  # ar to bd, early elution 
list.corrected.11 = read_excel(path.labeling, sheet = "ar_bd_EarlyElution") %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.11 = func.combine_sample_ID(dataset.tidy = list.corrected.11$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.11 = func.combine_sample_ID(dataset = list.corrected.11$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))



# Sheet 12:  # ar to bd, early elution 
list.corrected.12 = read_excel(path.labeling, sheet = "ar_bd_LateElution") %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.12 = func.combine_sample_ID(dataset.tidy = list.corrected.12$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.12 = func.combine_sample_ID(dataset = list.corrected.12$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))


# Sheet 13:  # be to bf
list.corrected.13 = read_excel(path.labeling, sheet = "be-bf_valine") %>% 
  flx.subtract_background(blankSamples =  c("blk2", "blk4") ) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.13 = func.combine_sample_ID(dataset.tidy = list.corrected.13$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.13 = func.combine_sample_ID(dataset = list.corrected.13$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))


# Sheet 14:  # bg to bk
list.corrected.14 = read_excel(path.labeling, sheet = "bg-bk") %>% 
  flx.subtract_background(blankSamples =  c("blk_3", "blk_4") ) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.14 = func.combine_sample_ID(dataset.tidy = list.corrected.14$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.14 = func.combine_sample_ID(dataset = list.corrected.14$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))

# ----------
# sheet 15: bl - bp: C18:1 and C18:2 
d15 = read_excel(path.labeling, sheet = "bl-bp")

# remove the second rep, and rename the sample to remove -1 in the sample ID
d15 = d15 %>% select(-contains("-2"))
colnames(d15) = colnames(d15) %>% str_remove(pattern = "-1")

list.corrected.15 = d15 %>% 
  flx.subtract_background(blankSamples =  c("blk_3", "blank_1")) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.15 = func.combine_sample_ID(dataset.tidy = list.corrected.15$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.15 = func.combine_sample_ID(dataset = list.corrected.15$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))


# sheet 16: bq - bs
d16 = read_excel(path.labeling, sheet = "bq-bs")
d16 = d16 %>% 
  # for mice with 3 replicates of blood collection (spaced by 10 min), take the 2nd collection
  select(-contains("-3")) %>% select(-contains("-1"))
colnames(d16) = colnames(d16) %>% str_remove("-2") %>% str_replace("-", "-tail-")

list.corrected.16 = d16 %>% 
  flx.subtract_background(blankSamples =  paste0("buffer_", 1:4)) %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.16 = func.combine_sample_ID(dataset.tidy = list.corrected.16$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.16 = func.combine_sample_ID(dataset = list.corrected.16$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))



# 
# sheet 17: G3P: be - bk
d17 = read_excel(path.labeling, sheet = "G3P_be_bk")
list.corrected.17 = d17 %>% flx.subtract_background(blankSamples = "Enz-blank") %>% 
  natural_abundance_correction(resolution = 12000)

d.normalized.tidy.17 = func.combine_sample_ID(dataset.tidy = list.corrected.17$Normalized %>% 
                                                gather(-c(Compound, C_Label), key = sample, value = enrichment) )
d.corrected.tidy.17 = func.combine_sample_ID(dataset = list.corrected.17$Corrected %>% 
                                               gather(-c(Compound, C_Label), key = sample, value = intensity))





# Compile all imported data
func.combine.tidies = function(inputList, cumulator) {
  for (i in 1:length(inputList)) {
    cumulator = rbind(cumulator, inputList[[i]])
  }
  return(cumulator)
}  


cumulator = NULL
d.normalized.tidy = func.combine.tidies(inputList = list(d.normalized.tidy.1, d.normalized.tidy.2, d.normalized.tidy.3,  d.normalized.tidy.4, 
                                                         d.normalized.tidy.5, d.normalized.tidy.6, d.normalized.tidy.7, d.normalized.tidy.8, 
                                                         d.normalized.tidy.9, d.normalized.tidy.10, d.normalized.tidy.11, d.normalized.tidy.12, 
                                                         d.normalized.tidy.13, d.normalized.tidy.14, d.normalized.tidy.15, d.normalized.tidy.16,
                                                         d.normalized.tidy.17), 
                                        cumulator = cumulator)

cumulator = NULL
d.corrected.tidy = tibble()
d.corrected.tidy = func.combine.tidies(inputList = list(d.corrected.tidy.1, d.corrected.tidy.2, d.corrected.tidy.3, d.corrected.tidy.4, 
                                                        d.corrected.tidy.5, d.corrected.tidy.6,  d.corrected.tidy.7,  d.corrected.tidy.8, 
                                                        d.corrected.tidy.9, d.corrected.tidy.10, d.corrected.tidy.11, d.corrected.tidy.12,
                                                        d.corrected.tidy.13, d.corrected.tidy.14, d.corrected.tidy.15, d.corrected.tidy.16,
                                                        d.corrected.tidy.17),
                                       cumulator = d.corrected.tidy)
d.corrected.tidy$blood %>% unique()
# check duplication
d.normalized.tidy %>% duplicated() %>% sum(); d.corrected.tidy %>% duplicated() %>% sum()




# Remove outliers from the compiled dataset; select only relevant metabolites 
samples.toRemove = c("am-tail-O30", "am-tail-O32", "ap-tail-L30", "ap-tail-L31",
                     "ac-tail-d3", "ac-tail-d2", "ah-tail-O18", "b-tail-O3",
                     "p-tail-d8", # tracer glycerol, glycerol labeling higher than usual, but no labeling in glucose 
                     "an-tail-O32", # tracer C16:0, extremely low labeling 
                     "O-art-O5", # tracer glycerol, there is no labeling in lactate and glucose in the artery blood
                     "O-art-d7", # tracer glycerol, little labeling in alanine
                     "am-tail-O16", # tracer glucose, higher infusion rate to label TG-glycerol, not ordinary infusion experiment
                     "e-art-d3", "e-art-O1", "e-tail-d3", "e-tail-d2", "e-tail-O1", # tracer lactate, abnormally low labeling in glucose
                     "ad-tail-O3", "ad-art-O3", "e-tail-O4", # tracer lactate: too much high labeling in tail labeling and too low Fcirc
                     "bc-tail-L64", # too low labeling, WT, palmitate infusion
                     "ar-tail-O59", "r-tail-O4", "s-tail-O7", "s-art-O7", # two low labeling, ob/ob, 3-HB infusion
                     "be-tail-L70", # too low labeling, WT, valine infusion
                     "bd-tail-L66", # too high enrichment at 60%, WT, valine infusion
                     "bk-tail-L64", # Valine, WT, extremely low labeling
                     # HFD, remove double cathetered mice, as the enrichment is consistently higher in serum than other genotypes and serum has unusual bright yellow corlor. 
                     "bg-art-H32", "bg-art-H33", "bh-art-H36", "bh-art-H37",
                     "bg-tail-H31",  "bg-tail-H32", "bg-tail-H33", "bh-tail-H35", "bh-tail-H36", "bh-tail-H37"
)


# fatty acid outliers
outlier.C16.0 <- c("bs-tail-L93", "br-tail-H53", "bq-tail-H51", "bf-tail-H19", "br-tail-H56", "br-tail-H57",
                   "br-tail-H51", "bq-tail-H56", "bs-tail-L94", "bf-tail-H8", "bf-tail-H3", "bs-tail-L92")

outlier.C18.1 <- c("bn-tail-H53", "bp-tail-H51", "bm-tail-H14", "br-tail-O84",
                   "br-tail-O86", "br-tail-O83", "bp-tail-O85",
                   
                   "au-tail-L66", "bo-tail-L93", "aw-tail-L63", "bm-tail-L82", "bm-tail-H7",
                   "bl-tail-H52", "au-tail-O61", "au-tail-O53",
                   
                   "aw-tail-O56", "br-tail-O85", "aw-tail-O60", "bi-tail-O82")

outlier.C18.2 <- c("ay-tail-L64", "ax-tail-L66", "bk-tail-L82", "bk-tail-H53",
                   "bk-tail-O82", "ax-tail-O61", "ax-tail-O57", "ay-tail-O60")

outlier.fattyacids <- c(outlier.C16.0, outlier.C18.1, outlier.C18.2)

samples.toRemove <- c(samples.toRemove, outlier.fattyacids)

func.RemoveOutlierSample = function(dataset, outliers){
  dataset %>% filter(! sample %in% outliers ) %>% filter(Compound %in% ordered.Compound) %>%   return()
}

d.corrected.tidy = func.RemoveOutlierSample(dataset = d.corrected.tidy, outliers = samples.toRemove)
d.normalized.tidy = func.RemoveOutlierSample(dataset = d.normalized.tidy, outliers = samples.toRemove)




# Remove the early experiments of C16:0 infusion where tracer enrichment is abnormally low
d.corrected.tidy = d.corrected.tidy %>% 
  filter(! ( (infused.tracer == "C16:0") & (infusion_round %in% c("q", "t")) ))

d.normalized.tidy = d.normalized.tidy %>% 
  filter(! ( (infused.tracer == "C16:0") & (infusion_round %in% c("q", "t")) ))


# check blood unique two levels
d.normalized.tidy.1$blood %>% unique()
d.normalized.tidy.2$blood %>% unique()
d.normalized.tidy.3$blood %>% unique()
d.normalized.tidy.4$blood %>% unique()


d.normalized.tidy.5$blood %>% unique()
d.normalized.tidy.6$blood %>% unique()
d.normalized.tidy.7$blood %>% unique()
d.normalized.tidy.8$blood %>% unique()
d.normalized.tidy.9$blood %>% unique()
d.normalized.tidy.10$blood %>% unique()
d.normalized.tidy.11$blood %>% unique()

d.normalized.tidy.12$blood %>% unique()
d.normalized.tidy.13$blood %>% unique()
d.normalized.tidy.14$blood %>% unique()
d.normalized.tidy.15$blood %>% unique()
d.normalized.tidy.16$blood %>% unique()
d.normalized.tidy.17$blood %>% unique()


# d.normalized.tidy.15[d.normalized.tidy.15$blood %>% is.na(), ] %>% view()
```


```{r, message=F, warning=FALSE,fig.height=6, fig.width=10, dpi=300, echo=F, results=F, fig.show='hide'}
# import data
# source("/Users/boyuan/Desktop/Harvard/Research/db db mice/Infusion data/Flux analysis script/import data.R")

# load workspace
# load("/Users/boyuan/Desktop/Harvard/Research/db db mice/Infusion data/Flux analysis script/import_data_workspace.RData")


# Calculate infusion carbon rate, normalized or standardized to the same infusion rate & same concentration tracer-wisely
# e.g., glucose concentration infused was around 200 mM but not exactly the same in different experiments; converge to 200 mM and adjust the labeling ratio in proportion
d.normalized.tidy = d.normalized.tidy %>%
  mutate(infusion_mouseID = str_c(infusion_round, "_", mouse_ID)) %>%
  
  # total carbon number of each metabolite
  group_by(Compound) %>% 
  mutate(C_Label.max = max(C_Label)) %>% ungroup() %>% 
  mutate(infusion_uL_perMin_g.BW = infusion_uL_perMin / BW) %>% 
  
  # combine with the standard infusion parameter database
  left_join(d.standardInfusionParameters, by = c("infused.tracer", "phenotype")) %>% 
  
  # adjust the enrichment in proportion to the infusion rate & tracer concentration normalization/standardization
  mutate(enrichment = ifelse (C_Label > 0, 
                              (tracer_conc_mM_Normalize / tracer_conc_mM) *( infusion_uL_perMin_g.BW_Normalize/infusion_uL_perMin_g.BW) * enrichment,
                              enrichment)) %>% 
  group_by(infusion_round, sample, Compound) 

# calculate the sum labeling of isotopes M+1, M+2...of each metabolite in each sample,
# to be subtracted from 1 as the updated parent labeling
d.normalized.tidy = d.normalized.tidy %>% filter(C_Label > 0) %>% 
  summarise(enrichment.isotope.sum = sum(enrichment, na.rm = T)) %>% 
  right_join(d.normalized.tidy) %>% 
  mutate(enrichment = ifelse(C_Label == 0,  1 - enrichment.isotope.sum, enrichment) ) %>% 
  
  # use the "standardized" concentration and infusion rate: replace the old two columns with new columns using same column name
  select(-c(tracer_conc_mM, infusion_uL_perMin_g.BW)) %>% 
  rename(tracer_conc_mM = tracer_conc_mM_Normalize, 
         infusion_uL_perMin_g.BW = infusion_uL_perMin_g.BW_Normalize) %>% # updated standardized tracer concentration and infusion rate
  
  # update into standardized tracer nmol 13C-atoms infused /min/animal
  mutate(infusion_nmol13C.atoms_perMin.gBW = tracer_conc_mM * infusion_uL_perMin_g.BW * C_Label.max_tracer,
         infusion_nmol13C.atoms_perMin = infusion_nmol13C.atoms_perMin.gBW * BW, 
         infusion_uL_perMin = infusion_uL_perMin_g.BW * BW) # update whole body infusion rate as well!





# Plot infusion parameters
# d.normalized.tidy %>%
#   ggplot(aes(x = infused.tracer, y = infusion_uL_perMin_g.BW, color = phenotype)) +
#   geom_point(position = "jitter", size = .1) + expand_limits(y = 0)
# 
# d.normalized.tidy %>%
#   ggplot(aes(x = infused.tracer, y = infusion_uL_perMin, color = phenotype)) +
#   geom_point(position = "jitter", size = .1) + expand_limits(y = 0)
# 
# d.normalized.tidy %>%
#   # filter(Compound == infused.tracer) %>%
#   ggplot(aes(x = infused.tracer, y = infusion_nmol13C.atoms_perMin, color = Compound)) +
#   geom_point(position = "jitter", size = .5, shape = 21) + expand_limits(y = 0) +
#   facet_wrap(~phenotype)







# Further remove failed experiments rounds as a block of data

# d.corrected.tidy = d.corrected.tidy %>% 
#   filter(! (infused.tracer == "C16:0" & infusion_round == "t")) %>% 
#   filter(! (infused.tracer == "C16:0" & infusion_round == "q")) 
# 
# d.normalized.tidy = d.normalized.tidy %>% 
#   filter(! (infused.tracer == "C16:0" & infusion_round == "t")) %>% 
#   filter(! (infused.tracer == "C16:0" & infusion_round == "q")) 





# color setup for C-label: same color assignment rule for all Compounds
colors = c ("grey", "firebrick", "yellow", "lightgreen",  "skyblue", "steelblue", "black")  # Specify the first seven colors (M+0, ...M + 6)

colors.more = colorRampPalette(brewer.pal(8, "Dark2"))( (nmax <- d.corrected.tidy$C_Label %>% as.numeric() %>% max()) - length(colors) + 1)
colors = c(colors, colors.more)
names(colors) = 0:nmax %>% factor(ordered = T)







# Plot enrichment in artery & tail blood for specified Compound ====
flx.plot_labeling_enrichment = function(listed.tidyData = listed.tidyData,
                                        mylabeled.compound.layer1 = NULL, # labeled metabolite
                                        enrichment_lower_bound = 0,
                                        facet.nrow = 1,
                                        show.TIC = T) {
  
  # Check there is listed data input
  if (is.null(listed.tidyData)) {
    stop("Please specify the dataset: the output from function \"flx.correct_natural_abundance\", which is in the format of a list.\n\n")
  }
  
  # Extract dataset from the list
  d.corrected.tidy = listed.tidyData$Corrected
  d.normalized.tidy = listed.tidyData$Normalized
  
  
  cmpd.all = d.corrected.tidy$Compound %>% unique()
  
  # Check there is Compound input
  if (is.null(mylabeled.compound.layer1 )) {
    stop("A Compound name must be specified in the argument of \"mylabeled.compound.layer1 = ... \" to make a plot.\n ")
  }
  
  # Check Compound is of length of one
  if (length(mylabeled.compound.layer1) > 1) {
    stop("Please input only one Compound in the argument of \"mylabeled.compound.layer1 = ... \" when making a plot.\n\n")
  }
  # Check Compound matches Compound names in the input listed.data
  if (! mylabeled.compound.layer1 %in% cmpd.all) {
    stop("Compound", " \"", mylabeled.compound.layer1, "\"", " is not found in the input dataset.\n" )
  }
  
  
  
  
  # Convert C-label into ordered factor for visualization purpose
  ordered.C_label = d.normalized.tidy $ C_Label %>% unique() %>% rev()
  d.normalized.tidy$C_Label = factor(d.normalized.tidy $ C_Label, levels = ordered.C_label, ordered = T)
  d.corrected.tidy$C_Label = factor(d.corrected.tidy$C_Label, levels = ordered.C_label, ordered = T)
  
  
  # Select specified Compound and tidy up
  d.corrected.tidy = d.corrected.tidy %>% filter(Compound == mylabeled.compound.layer1) 
  
  d.TIC.tidy = d.corrected.tidy %>% group_by(sample, Compound) %>%
    summarise(TIC = sum(intensity, na.rm = T),
              phenotype = unique(phenotype))
  
  d.normalized.tidy = d.normalized.tidy %>%  filter(Compound == mylabeled.compound.layer1) 
  
  
  # max TIC intens.
  TIC.max = (d.TIC.tidy)$TIC %>% max(na.rm = T)
  # Number of color
  C_label.i = d.normalized.tidy$C_Label %>% unique() %>% as.character()
  
  
  # Define plotting function
  theme_set(theme_bw() +
              theme(#axis.text.x = element_text(angle = 45, hjust = 1),
                strip.background = element_blank(),
                strip.text = element_text(size = 14, face = "bold"),
                panel.grid = element_blank(),
                panel.border = element_rect(colour = "black", size = 1),
                axis.text = element_text(colour = "black", size = 11),
                title = element_text(face = "bold", hjust = .5, size = 12),
                plot.title = element_text(hjust = .5, size = 16),
                legend.title = element_blank()) )
  
  
  # Label fraction bar plot
  plt.bar = d.normalized.tidy %>%
    ggplot(aes(x = sample)) +
    geom_bar(aes(y = enrichment, fill = C_Label, color = C_Label),
             stat = "identity", alpha = .8) +
    
    
    scale_color_manual(values = colors [C_label.i %>% as.character()] ) +
    scale_fill_manual(values = colors [C_label.i %>% as.character()] ) +
    labs(x = " ", y = "Labelling fraction\n", title = mylabeled.compound.layer1)  + # \n increase y axis - text gap
    scale_x_discrete(expand = c(0, 0)) +
    coord_cartesian(ylim = c(enrichment_lower_bound, 1)) +
    scale_y_continuous(expand = c(0, 0),
                       # Need this right side axis as place holder
                       sec.axis = sec_axis(~.*TIC.max, name = "Total isotopologues ion counts\n")) +
    theme(axis.text.x = element_text(angle = 60, hjust = 1, color = ifelse(show.TIC == F, "black", "white") ),
          axis.text.y.right = element_text(color = NA),  # turn off TIC axis text
          axis.title.y.right = element_text(colour = NA),
          axis.ticks.y.right = element_blank() ) # turn off TIC ticks
  
  
  # TIC line plot
  plt.TIC = d.TIC.tidy %>%
    ggplot(aes(x = sample)) +
    
    # set bar plot (transparent) so as to keep the legend as a place holder to allow overlay with real bar plot
    geom_bar(aes(y = TIC),
             stat = "identity", alpha = 0, color = NA, position = "fill") +
    
    
    # scale_color_manual(values = colors) +
    # scale_fill_manual(values = colors) +
    labs(x = " ", y = "Labelling fraction\n", title = mylabeled.compound.layer1)  + # \n increase y axis - text gap
    scale_x_discrete(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0),
                       sec.axis = sec_axis(~.*TIC.max, name = "Total isotopologues ion counts\n")) +
    
    theme(panel.background = element_blank(),
          
          # turn on bar plot as place holder for legend, but not show legend here
          # so as to show legend of the bar plot
          legend.background = element_blank(),
          legend.key = element_blank(),
          legend.text = element_blank(),
          
          plot.background = element_blank(),
          axis.ticks.y.left = element_blank(), # turn off label fraction axis ticks
          axis.text.x = element_text(angle = 60, hjust = 1, colour = "black"),
          axis.ticks.x = element_blank(),
          axis.text.y.left = element_text(colour = NA), # turn off label fraction axis text
          axis.title.y.left = element_text(colour = NA) # turn off label fraction axis title
    )  +
    
    # TIC counts
    geom_point(aes(y = TIC  / TIC.max), fill = "black", color = "white", alpha = 1, size = 3, shape = 23, stroke = 1 ) 
  # geom_line(aes(y = TIC  / TIC.max, group = 1), color = "black", alpha = .5)
  
  
  # facet
  plt.TIC = plt.TIC + 
    facet_wrap( ~ phenotype, scales = "free_x", nrow = facet.nrow) + 
    theme(panel.spacing = unit(1, "lines"))
  
  plt.bar = plt.bar + 
    facet_wrap( ~ phenotype, scales = "free_x", nrow = facet.nrow) + 
    theme(panel.spacing = unit(1, "lines"))
  
  
  
  # Overlay and align up the two plots
  if (show.TIC == T) {
    aligned_plots <- align_plots(plt.bar, plt.TIC, align="hv", axis="tblr")
    ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])
  } else { return(plt.bar)}
  
  
}





flx.plot_labeling_enrichment.which.Tracer.Blood = function(my.infused.tracer = "Glucose", 
                                                           mylabeled.compound.layer2 = "Glucose",
                                                           plotBlood = "tail", 
                                                           enrichment_lower_bound = 0,
                                                           showTIC = F){
  
  listed.tidyData = list(Normalized = d.normalized.tidy %>% filter(infused.tracer == my.infused.tracer & blood == plotBlood), 
                         Corrected = d.corrected.tidy %>% filter(infused.tracer == my.infused.tracer & blood == plotBlood))
  
  p = flx.plot_labeling_enrichment(listed.tidyData = listed.tidyData, 
                                   mylabeled.compound.layer1 = mylabeled.compound.layer2,
                                   enrichment_lower_bound = enrichment_lower_bound, show.TIC = showTIC)
  
  plot_grid(ggplot() + theme_void() + ggtitle(paste("Infused tracer: ", my.infused.tracer, "; ", plotBlood, " blood")) +
              theme(plot.title = element_text(hjust = .4, face = "bold", size = 15, color = ifelse(plotBlood == "art", "firebrick", "steelblue"))),
            p, 
            rel_heights = c(1, 15), nrow = 2 ) 
}
```


```{r, message=F, warning=FALSE,fig.height=5, fig.width=10, dpi=300, echo=F}

infused.tracers <- d.normalized.tidy$infused.tracer %>% unique()
infused.tracers <- infused.tracers[-8] # remove acetate

labeled.metabolite = infused.tracers

for (tracer.i in infused.tracers){
  
  for (metabolite.i in labeled.metabolite) {
    
    paste("tracer:", tracer.i, "; labeled metabolite: ", metabolite.i) %>% print()
    
    plt.i <- flx.plot_labeling_enrichment.which.Tracer.Blood(my.infused.tracer = tracer.i, 
                                                  mylabeled.compound = metabolite.i,
                                                  plotBlood = "tail", enrichment_lower_bound = .6)
    
    print(plt.i)
    
  }
  
    
}



```





